version: '3.8'
services:
  divarbot:
    build: .
    container_name: divarbot_container
    restart: unless-stopped
    image: divarbot_image
    volumes:
      - logfile_volume:/data

volumes:
  logfile_volume: